server.port=8081

spring.application.name=productor-senales

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=admin
spring.rabbitmq.password=admin123

rabbitmq.queue.alertas=cola.alertas.vitales
rabbitmq.queue.resumen=cola.resumen.vitales