server.port=8084

spring.application.name=consumidor-json

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=admin
spring.rabbitmq.password=admin123

rabbitmq.queue.resumen=cola.resumen.vitales

alertas.json.directorio=C:/medialert/alertas-json